import { z } from 'zod';

// Primitive field types available in the model designer
export const fieldTypeSchema = z.enum([
  'string',
  'int',
  'long',
  'decimal',
  'double',
  'float',
  'bool',
  'DateTime',
  'DateOnly',
  'TimeOnly',
  'Guid',
  'byte[]',
  'json',
]);

export type FieldType = z.infer<typeof fieldTypeSchema>;

// Field constraints
export const fieldConstraintsSchema = z.object({
  isRequired: z.boolean().default(false),
  isUnique: z.boolean().default(false),
  isPrimaryKey: z.boolean().default(false),
  isAutoGenerated: z.boolean().default(false),
  maxLength: z.number().optional(),
  minLength: z.number().optional(),
  precision: z.number().optional(),
  scale: z.number().optional(),
  defaultValue: z.string().optional(),
  regex: z.string().optional(),
});

export type FieldConstraints = z.infer<typeof fieldConstraintsSchema>;

const defaultConstraints = {
  isRequired: false,
  isUnique: false,
  isPrimaryKey: false,
  isAutoGenerated: false,
};

// Entity field definition
export const fieldSchema = z.object({
  id: z.string(),
  name: z.string().min(1, 'Field name is required'),
  type: fieldTypeSchema,
  constraints: fieldConstraintsSchema.default(defaultConstraints),
  description: z.string().optional(),
  annotations: z.array(z.string()).default([]),
});

export type Field = z.infer<typeof fieldSchema>;

// Relation cardinality
export const cardinalitySchema = z.enum(['one-to-one', 'one-to-many', 'many-to-many']);
export type Cardinality = z.infer<typeof cardinalitySchema>;

// Relation between entities
export const relationSchema = z.object({
  id: z.string(),
  name: z.string(),
  sourceEntityId: z.string(),
  targetEntityId: z.string(),
  cardinality: cardinalitySchema,
  sourceFieldId: z.string().optional(), // FK field
  targetFieldId: z.string().optional(), // Referenced field (usually PK)
  onDelete: z.enum(['cascade', 'restrict', 'setNull', 'noAction']).default('noAction'),
  onUpdate: z.enum(['cascade', 'restrict', 'setNull', 'noAction']).default('noAction'),
});

export type Relation = z.infer<typeof relationSchema>;

// Entity position on canvas
export const positionSchema = z.object({
  x: z.number(),
  y: z.number(),
});

export type Position = z.infer<typeof positionSchema>;

// Entity color theme
export const entityColorSchema = z.enum(['blue', 'purple', 'green', 'orange', 'pink', 'cyan']);
export type EntityColor = z.infer<typeof entityColorSchema>;

// Entity definition
export const entitySchema = z.object({
  id: z.string(),
  name: z.string().min(1, 'Entity name is required'),
  tableName: z.string().optional(), // Custom table name if different from entity name
  fields: z.array(fieldSchema).default([]),
  position: positionSchema,
  color: entityColorSchema.default('blue'),
  description: z.string().optional(),
  isAbstract: z.boolean().default(false),
  baseEntityId: z.string().optional(), // For inheritance
});

export type Entity = z.infer<typeof entitySchema>;

// Index definition
export const indexSchema = z.object({
  id: z.string(),
  name: z.string(),
  entityId: z.string(),
  fieldIds: z.array(z.string()),
  isUnique: z.boolean().default(false),
  isClustered: z.boolean().default(false),
});

export type Index = z.infer<typeof indexSchema>;

// Complete data model (workspace/project)
export const dataModelSchema = z.object({
  id: z.string(),
  name: z.string().min(1, 'Model name is required'),
  description: z.string().optional(),
  entities: z.array(entitySchema).default([]),
  relations: z.array(relationSchema).default([]),
  indexes: z.array(indexSchema).default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  version: z.number().default(1),
});

export type DataModel = z.infer<typeof dataModelSchema>;

// Workspace containing multiple models
export const workspaceSchema = z.object({
  id: z.string(),
  name: z.string().min(1, 'Workspace name is required'),
  models: z.array(dataModelSchema).default([]),
  activeModelId: z.string().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export type Workspace = z.infer<typeof workspaceSchema>;

// Export validation helpers
export const validateEntity = (data: unknown) => entitySchema.safeParse(data);
export const validateField = (data: unknown) => fieldSchema.safeParse(data);
export const validateRelation = (data: unknown) => relationSchema.safeParse(data);
export const validateDataModel = (data: unknown) => dataModelSchema.safeParse(data);
